/* ============================================================================
   MOTORA — mock catalog (fictional brands & models)
   Shape mirrors a future REST API: /vehicles, /vehicles/:id, /brands, /reviews.
   Includes deliberate edge cases: missing price, no reviews, no image art,
   very long names, incomplete specs, upcoming / discontinued availability.
   ============================================================================ */

export const CAR_CATEGORIES = [
  { id: "suv",         label: "SUV",         ico: "🚙" },
  { id: "sedan",       label: "Sedan",       ico: "🚗" },
  { id: "hatchback",   label: "Hatchback",   ico: "🚘" },
  { id: "coupe",       label: "Coupe",       ico: "🏎️" },
  { id: "luxury",      label: "Luxury",      ico: "💎" },
  { id: "ev",          label: "Electric",    ico: "⚡" },
  { id: "hybrid",      label: "Hybrid",      ico: "🔋" },
  { id: "offroad",     label: "Off-road",    ico: "⛰️" },
  { id: "convertible", label: "Convertible", ico: "🌤️" },
];

export const BIKE_CATEGORIES = [
  { id: "sports",     label: "Sports",      ico: "🏍️" },
  { id: "cruiser",    label: "Cruiser",     ico: "🛣️" },
  { id: "naked",      label: "Naked",       ico: "🔩" },
  { id: "adventure",  label: "Adventure",   ico: "🧭" },
  { id: "scooter",    label: "Scooter",     ico: "🛵" },
  { id: "commuter",   label: "Commuter",    ico: "🏙️" },
  { id: "electric",   label: "Electric",    ico: "⚡" },
  { id: "touring",    label: "Touring",     ico: "🗺️" },
  { id: "caferacer",  label: "Café Racer",  ico: "☕" },
];

const R = (author, rating, title, content, extra = {}) => ({
  author, rating, title, content,
  date: extra.date || "2026-05-12",
  verified: extra.verified ?? true,
  ownership: extra.ownership || "Owner",
  variant: extra.variant || null,
  pros: extra.pros || [], cons: extra.cons || [],
  helpful: extra.helpful ?? Math.floor(rating * 7),
});

export const VEHICLES = [
  /* ============================== CARS ============================== */
  {
    id: "aurelion-sovereign-gt", type: "car", brand: "Aurelion", model: "Sovereign GT",
    category: "luxury", price: 2850000, searches: 98200, rating: 4.8, availability: "New",
    fuel: "Petrol", transmission: "8AT", drivetrain: "AWD", seating: 4,
    power: "780 hp", torque: "900 Nm", mileage: "6.4 km/l", safety: 5, adas: true, sunroof: true,
    tags: ["Track Inspired", "Torque Focused"], hue: 218,
    highlight: "Hand-built 6.0L V12 grand tourer",
    colors: ["Regal Sapphire", "Ivory Pearl", "Obsidian"],
    variants: [
      { name: "GT",        price: 2850000, power: "780 hp", mileage: "6.4 km/l" },
      { name: "GT Vitesse", price: 3220000, power: "830 hp", mileage: "6.0 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "6.0L V12 twin-turbo", "Displacement": "5998 cc", "Power": "780 hp @ 6500 rpm", "Torque": "900 Nm @ 2300 rpm", "0–100 km/h": "3.1 s", "Top speed": "330 km/h", "Transmission": "8-speed automatic", "Drivetrain": "AWD" },
      "Dimensions & Capacity": { "Length": "5,015 mm", "Wheelbase": "2,940 mm", "Seating": "4", "Boot space": "420 L", "Kerb weight": "2,120 kg", "Fuel tank": "90 L" },
      "Comfort & Safety": { "Airbags": "10", "ADAS": "Level 2+ (adaptive cruise, lane keep)", "Sunroof": "Panoramic", "Suspension": "Adaptive air", "Brakes": "Carbon-ceramic discs", "Warranty": "5 yr / unlimited km" },
    },
    pros: ["Effortless V12 surge", "Cathedral-quiet cabin", "Concours-level finish"],
    cons: ["Thirsty in the city", "Tight rear headroom"],
    reviews: [
      R("Dhruv S.", 5, "The definition of arrival", "Six months and 9,000 km in — the Sovereign turns every motorway into a private lounge. The V12 never feels stressed.", { variant: "GT", pros: ["Ride comfort", "Power delivery"], cons: ["Fuel bills"], helpful: 41 }),
      R("Elena M.", 4.5, "Grand touring, properly", "Crossed three countries in a weekend without a hint of fatigue. ADAS is genuinely useful, not gimmicky.", { ownership: "Owner", helpful: 28 }),
    ],
  },
  {
    id: "stratos-veloce-rs", type: "car", brand: "Stratos Dynamics", model: "Veloce RS",
    category: "coupe", price: 1980000, searches: 154300, rating: 4.7, availability: "New",
    fuel: "Petrol", transmission: "7DCT", drivetrain: "RWD", seating: 2,
    power: "640 hp", torque: "720 Nm", mileage: "7.8 km/l", safety: 5, adas: true, sunroof: false,
    tags: ["Track Inspired"], hue: 355,
    highlight: "Mid-engine carbon-tub coupe",
    colors: ["Rosso Vela", "Nardo Grey"],
    variants: [
      { name: "RS",       price: 1980000, power: "640 hp", mileage: "7.8 km/l" },
      { name: "RS Corsa", price: 2310000, power: "690 hp", mileage: "7.2 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "4.0L V8 biturbo (mid)", "Displacement": "3982 cc", "Power": "640 hp @ 6800 rpm", "Torque": "720 Nm @ 2800 rpm", "0–100 km/h": "3.0 s", "Top speed": "325 km/h", "Transmission": "7-speed DCT", "Drivetrain": "RWD" },
      "Dimensions & Capacity": { "Length": "4,560 mm", "Seating": "2", "Boot space": "150 L", "Kerb weight": "1,480 kg", "Fuel tank": "68 L" },
      "Comfort & Safety": { "Airbags": "6", "ADAS": "Adaptive cruise + AEB", "Suspension": "Double wishbone, magnetorheological", "Brakes": "Carbon-ceramic", "Tyres": "245/35 R20 · 305/30 R20", "Warranty": "3 yr / 100,000 km" },
    },
    pros: ["Scalpel steering", "Soundtrack for days"], cons: ["Firm ride", "Two seats only"],
    reviews: [
      R("Kabir A.", 5, "Track day royalty", "Lapped all summer without a hiccup. Brakes never fade, chassis talks to you constantly.", { variant: "RS Corsa", helpful: 52 }),
    ],
  },
  {
    id: "novacore-pulse-x", type: "car", brand: "Novacore", model: "Pulse X",
    category: "ev", price: 720000, searches: 231800, rating: 4.6, availability: "New",
    fuel: "Electric", transmission: "1AT", drivetrain: "AWD", seating: 5,
    power: "525 hp", torque: "740 Nm", mileage: "610 km range", safety: 5, adas: true, sunroof: true,
    tags: ["EV Ready", "City Agile"], hue: 190,
    highlight: "610 km real-world range flagship EV",
    colors: ["Glacier White", "Cobalt Flow", "Slate"],
    variants: [
      { name: "Standard", price: 720000, power: "402 hp", mileage: "520 km range" },
      { name: "Dual Motor X", price: 860000, power: "525 hp", mileage: "610 km range" },
    ],
    specs: {
      "Powertrain": { "Motor": "Dual PMSM", "Power": "525 hp", "Torque": "740 Nm", "0–100 km/h": "3.9 s", "Battery": "102 kWh NMC", "Range (WLTP)": "610 km", "DC fast charge": "10–80% in 24 min", "Drivetrain": "AWD" },
      "Dimensions & Capacity": { "Length": "4,860 mm", "Seating": "5", "Boot space": "520 L + 88 L frunk", "Kerb weight": "2,090 kg" },
      "Comfort & Safety": { "Airbags": "8", "ADAS": "Highway pilot L2+", "Sunroof": "Fixed glass", "V2L": "3.6 kW", "Warranty": "8 yr battery / 160,000 km" },
    },
    pros: ["Real 600 km range", "24-minute charge stops", "Huge frunk"],
    cons: ["Touch-only controls divide opinion"],
    reviews: [
      R("Priya N.", 5, "Silence is the new luxury", "Commuting costs fell off a cliff. Charging twice a month, tops.", { variant: "Dual Motor X", pros: ["Range", "Running cost"], helpful: 64 }),
      R("Tomás R.", 4, "Almost perfect", "Wish it kept a few physical buttons, but the drivetrain is faultless.", { helpful: 23 }),
      R("Ayesha K.", 4.5, "Family approved", "Cabin swallows two child seats and a dog. One-pedal drive is addictive.", { ownership: "Owner", helpful: 19 }),
    ],
  },
  {
    id: "vanterra-ridgeline-trailmaster-overland-edition", type: "car",
    brand: "Vanterra", model: "Ridgeline Trailmaster Overland Expedition Edition", /* edge: long name */
    category: "offroad", price: 985000, searches: 87400, rating: 4.5, availability: "New",
    fuel: "Diesel", transmission: "10AT", drivetrain: "4WD", seating: 7,
    power: "410 hp", torque: "850 Nm", mileage: "9.6 km/l", safety: 5, adas: true, sunroof: true,
    tags: ["Torque Focused"], hue: 95,
    highlight: "Locking diffs, 900 mm wading depth",
    colors: ["Canyon Bronze", "Basalt"],
    variants: [{ name: "Overland", price: 985000, power: "410 hp", mileage: "9.6 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "3.5L I6 turbo-diesel", "Power": "410 hp", "Torque": "850 Nm", "Transmission": "10-speed automatic", "Drivetrain": "4WD, low-range + rear locker", "Wading depth": "900 mm", "Ground clearance": "285 mm" },
      "Dimensions & Capacity": { "Length": "5,120 mm", "Seating": "7", "Boot space": "480–2,100 L", "Towing": "3,500 kg", "Fuel tank": "110 L" },
      "Comfort & Safety": { "Airbags": "9", "ADAS": "Off-road cruise + 360° cam", "Suspension": "Long-travel coil", "Warranty": "5 yr / 150,000 km" },
    },
    pros: ["Goes anywhere, seats seven", "Monster torque"], cons: ["Sheer size in town"],
    reviews: [R("Marcus O.", 4.5, "Expedition proven", "Four weeks across the high desert. Zero drama, huge range with the 110 L tank.", { helpful: 31 })],
  },
  {
    id: "hoshi-aria", type: "car", brand: "Hoshi", model: "Aria",
    category: "hatchback", price: 145000, searches: 305400, rating: 4.4, availability: "New",
    fuel: "Petrol", transmission: "CVT", drivetrain: "FWD", seating: 5,
    power: "120 hp", torque: "145 Nm", mileage: "21.5 km/l", safety: 4, adas: false, sunroof: false,
    tags: ["City Agile"], hue: 42,
    highlight: "The everyday hatch that sips fuel",
    colors: ["Lunar Silver", "Coral Red", "Deep Teal"],
    variants: [
      { name: "S",  price: 145000, power: "120 hp", mileage: "21.5 km/l" },
      { name: "SX", price: 168000, power: "120 hp", mileage: "21.0 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "1.2L I3 petrol", "Power": "120 hp", "Torque": "145 Nm", "Transmission": "CVT", "Mileage (ARAI)": "21.5 km/l" },
      "Dimensions & Capacity": { "Length": "3,990 mm", "Seating": "5", "Boot space": "310 L", "Kerb weight": "1,020 kg", "Fuel tank": "37 L" },
      "Comfort & Safety": { "Airbags": "6", "Rear camera": "Yes", "Warranty": "3 yr / 100,000 km" },
    },
    pros: ["Sips fuel", "Easy to park", "6 airbags standard"], cons: ["Modest highway punch"],
    reviews: [
      R("Nithya V.", 4.5, "First car, right car", "A year of city duty and one tank lasts forever. Light steering is a blessing in traffic.", { helpful: 44 }),
      R("Rahul D.", 4, "Honest machine", "Nothing flashy, everything works. Rear seat is fine for two adults.", { verified: false, ownership: "Test drive", helpful: 9 }),
    ],
  },
  {
    id: "belmonte-solstice-cabrio", type: "car", brand: "Belmonte", model: "Solstice Cabrio",
    category: "convertible", price: 1120000, searches: 64100, rating: 4.3, availability: "New",
    fuel: "Petrol", transmission: "8AT", drivetrain: "RWD", seating: 4,
    power: "380 hp", torque: "500 Nm", mileage: "10.2 km/l", safety: 4, adas: true, sunroof: false,
    tags: ["Track Inspired"], hue: 28,
    highlight: "12-second folding hardtop, four real seats",
    colors: ["Amalfi Blue", "Champagne"],
    variants: [{ name: "Cabrio", price: 1120000, power: "380 hp", mileage: "10.2 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "3.0L I6 turbo", "Power": "380 hp", "Torque": "500 Nm", "0–100 km/h": "4.9 s", "Transmission": "8-speed automatic", "Drivetrain": "RWD" },
      "Dimensions & Capacity": { "Length": "4,720 mm", "Seating": "4", "Boot space": "280 L (roof down)", "Kerb weight": "1,790 kg" },
      "Comfort & Safety": { "Airbags": "8", "Roof": "Folding hardtop, 12 s to 50 km/h", "Wind deflector": "Standard", "Warranty": "4 yr / 120,000 km" },
    },
    pros: ["Open-air grand touring", "Usable rear seats"], cons: ["Boot shrinks roof-down"],
    reviews: [],  /* edge: no reviews yet */
  },
  {
    id: "kestrel-meridian", type: "car", brand: "Kestrel", model: "Meridian",
    category: "sedan", price: 425000, searches: 189700, rating: 4.5, availability: "New",
    fuel: "Hybrid", transmission: "eCVT", drivetrain: "FWD", seating: 5,
    power: "218 hp", torque: "221 Nm", mileage: "23.8 km/l", safety: 5, adas: true, sunroof: true,
    tags: ["EV Ready", "City Agile"], hue: 160,
    highlight: "Self-charging hybrid executive sedan",
    colors: ["Emerald Mist", "Platinum", "Midnight"],
    variants: [
      { name: "Hybrid",       price: 425000, power: "218 hp", mileage: "23.8 km/l" },
      { name: "Hybrid Luxe",  price: 489000, power: "218 hp", mileage: "23.1 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "2.0L I4 + e-motor", "System power": "218 hp", "Transmission": "eCVT", "Mileage (ARAI)": "23.8 km/l", "EV-only mode": "Up to 2 km city crawl" },
      "Dimensions & Capacity": { "Length": "4,780 mm", "Seating": "5", "Boot space": "470 L" },
      "Comfort & Safety": { "Airbags": "8", "ADAS": "Full suite standard", "Sunroof": "Tilt/slide", "Warranty": "8 yr hybrid battery" },
    },
    pros: ["Diesel-beating economy", "Serene drivetrain"], cons: ["eCVT drone when pushed"],
    reviews: [R("Grace L.", 4.5, "The sensible flagship", "40% of my city driving happens on electrons. Rear seat comfort surprises everyone.", { helpful: 27 })],
  },
  {
    id: "solaris-corsa-e", type: "car", brand: "Solaris", model: "Corsa-E",
    category: "ev", price: 265000, searches: 176200, rating: 4.2, availability: "Upcoming",
    fuel: "Electric", transmission: "1AT", drivetrain: "FWD", seating: 5,
    power: "204 hp", torque: "310 Nm", mileage: "445 km range", safety: 4, adas: true, sunroof: false,
    tags: ["EV Ready", "City Agile"], hue: 265,
    highlight: "Compact EV crossover — launching next quarter",
    colors: ["Violet Haze", "Pure White"],
    variants: [{ name: "Launch Edition", price: 265000, power: "204 hp", mileage: "445 km range" }],
    specs: {
      "Powertrain": { "Motor": "Single PMSM", "Power": "204 hp", "Battery": "62 kWh LFP", "Range (claimed)": "445 km", "DC fast charge": "10–80% in 31 min" },
      "Dimensions & Capacity": { "Length": "4,310 mm", "Seating": "5", "Boot space": "410 L" },
      "Comfort & Safety": { "Airbags": "6", "ADAS": "L2 highway assist" },
    },
    pros: ["Sharp pricing", "LFP longevity"], cons: ["Not on sale yet"],
    reviews: [],
  },
  {
    id: "aurelion-vela-lwb", type: "car", brand: "Aurelion", model: "Vela LWB",
    category: "luxury", price: 1750000, searches: 45800, rating: 4.6, availability: "New",
    fuel: "Petrol", transmission: "9AT", drivetrain: "AWD", seating: 5,
    power: "460 hp", torque: "600 Nm", mileage: "8.9 km/l", safety: 5, adas: true, sunroof: true,
    tags: ["Torque Focused"], hue: 230,
    highlight: "Chauffeur-spec long wheelbase limousine",
    colors: ["Imperial Navy", "Moonstone"],
    variants: [{ name: "LWB", price: 1750000, power: "460 hp", mileage: "8.9 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "4.4L V8 twin-turbo", "Power": "460 hp", "Torque": "600 Nm", "Transmission": "9-speed automatic", "Drivetrain": "AWD" },
      "Dimensions & Capacity": { "Length": "5,390 mm", "Wheelbase": "3,215 mm", "Seating": "5 (4-seat lounge opt.)", "Boot space": "510 L" },
      "Comfort & Safety": { "Airbags": "10", "Rear lounge": "Reclining, heated, massaging", "ADAS": "L2+ with chauffeur park", "Warranty": "5 yr" },
    },
    pros: ["Best rear seat this side of a jet"], cons: ["You'll want a driver"],
    reviews: [R("W. Chen", 5, "Board-room on wheels", "The rear cabin is where this car earns its price. Isolation is uncanny.", { helpful: 18 })],
  },
  {
    id: "hoshi-vector-s", type: "car", brand: "Hoshi", model: "Vector S",
    category: "suv", price: 385000, searches: 254900, rating: 4.4, availability: "New",
    fuel: "Petrol", transmission: "6MT", drivetrain: "FWD", seating: 5,
    power: "158 hp", torque: "250 Nm", mileage: "16.8 km/l", safety: 5, adas: false, sunroof: true,
    tags: ["City Agile"], hue: 12,
    highlight: "The family SUV sweet spot",
    colors: ["Sunrise Orange", "Storm Grey", "White"],
    variants: [
      { name: "S MT",  price: 385000, power: "158 hp", mileage: "16.8 km/l" },
      { name: "S CVT", price: 412000, power: "158 hp", mileage: "16.2 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "1.5L I4 turbo", "Power": "158 hp", "Torque": "250 Nm", "Transmission": "6-speed manual / CVT", "Mileage": "16.8 km/l" },
      "Dimensions & Capacity": { "Length": "4,420 mm", "Seating": "5", "Boot space": "433 L", "Ground clearance": "208 mm" },
      "Comfort & Safety": { "Airbags": "6", "Sunroof": "Panoramic", "Warranty": "3 yr / 100,000 km" },
    },
    pros: ["Value-packed", "Panoramic roof standard"], cons: ["No ADAS option"],
    reviews: [R("Farid H.", 4, "Does everything well", "18 months in — flawless. CVT is the one to buy in traffic.", { variant: "S CVT", helpful: 33 })],
  },
  {
    id: "stratos-quantum-gt-e", type: "car", brand: "Stratos Dynamics", model: "Quantum GT-E",
    category: "ev", price: 2450000, searches: 121500, rating: 4.7, availability: "New",
    fuel: "Electric", transmission: "2AT", drivetrain: "AWD", seating: 4,
    power: "1,020 hp", torque: "1,420 Nm", mileage: "540 km range", safety: 5, adas: true, sunroof: true,
    tags: ["Track Inspired", "EV Ready"], hue: 200,
    highlight: "Four-figure horsepower, zero emissions",
    colors: ["Photon Silver", "Void Black"],
    variants: [{ name: "GT-E", price: 2450000, power: "1,020 hp", mileage: "540 km range" }],
    specs: {
      "Powertrain": { "Motors": "Tri-motor", "Power": "1,020 hp", "Torque": "1,420 Nm", "0–100 km/h": "2.4 s", "Battery": "108 kWh", "Range": "540 km", "800V charging": "10–80% in 19 min" },
      "Dimensions & Capacity": { "Length": "4,980 mm", "Seating": "4", "Boot space": "360 L + frunk" },
      "Comfort & Safety": { "Airbags": "9", "ADAS": "L2+ with track telemetry", "Brakes": "Carbon-ceramic + regen", "Warranty": "8 yr battery" },
    },
    pros: ["Violent acceleration, silently"], cons: ["Weight shows on tight tracks"],
    reviews: [R("Ines P.", 5, "Physics, renegotiated", "2.4 seconds is not a number, it's an event. Range holds up at speed too.", { helpful: 47 })],
  },
  {
    id: "belmonte-classica-1969", type: "car", brand: "Belmonte", model: "Classica '69 Heritage",
    category: "coupe", price: null, searches: 38100, rating: 0, availability: "Discontinued",  /* edges: no price, no rating */
    fuel: "Petrol", transmission: "5MT", drivetrain: "RWD", seating: 2,
    power: "300 hp", torque: "410 Nm", mileage: "—", safety: 3, adas: false, sunroof: false,
    tags: [], hue: 340, noArt: true,  /* edge: no image art */
    highlight: "Collector classic — price on request",
    colors: ["Heritage Red"],
    variants: [{ name: "Heritage", price: null, power: "300 hp", mileage: "—" }],
    specs: {
      "Engine & Performance": { "Engine": "5.7L V8 (carburetted)", "Power": "300 hp", "Transmission": "5-speed manual" },
    },
    pros: ["Rolling art"], cons: ["Parts hunt required"],
    reviews: [],
  },

  /* ============================== BIKES ============================== */
  {
    id: "ryujin-katana-rr", type: "bike", brand: "Ryujin", model: "Katana RR",
    category: "sports", price: 285000, searches: 264800, rating: 4.7, availability: "New",
    fuel: "Petrol", transmission: "6MT (quickshifter)", cooling: "Liquid", abs: "Dual-channel, cornering",
    power: "205 hp", torque: "113 Nm", mileage: "14.5 km/l", kerb: "201 kg", seatHeight: "832 mm",
    tags: ["Track Inspired"], hue: 348,
    highlight: "Litre-class superbike with winglets",
    colors: ["Racing Crimson", "Pearl White"],
    variants: [
      { name: "RR",     price: 285000, power: "205 hp", mileage: "14.5 km/l" },
      { name: "RR SP",  price: 342000, power: "205 hp", mileage: "14.1 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "999cc inline-4", "Power": "205 hp @ 13,200 rpm", "Torque": "113 Nm @ 11,000 rpm", "Transmission": "6-speed, bi-directional quickshifter", "Cooling": "Liquid", "Riding modes": "5 + custom" },
      "Chassis & Dimensions": { "Kerb weight": "201 kg", "Seat height": "832 mm", "Fuel tank": "16.1 L", "Ground clearance": "130 mm" },
      "Braking & Suspension": { "Front brake": "Dual 330 mm, radial calipers", "ABS": "Cornering ABS", "Front suspension": "43 mm USD, fully adjustable", "Tyres": "120/70 ZR17 · 200/55 ZR17", "Warranty": "3 yr" },
    },
    pros: ["Electronics safety net", "Stable at silly speeds"], cons: ["Committed riding position"],
    reviews: [
      R("Zoya F.", 5, "Track weapon, road manners", "Cornering ABS saved me once in the wet — worth every rupee.", { variant: "RR SP", helpful: 39 }),
      R("Dan W.", 4.5, "The benchmark", "Quickshifter is telepathic. Mirrors are decorative, as tradition demands.", { helpful: 22 }),
    ],
  },
  {
    id: "apexforge-titan-1200", type: "bike", brand: "Apex Forge", model: "Titan 1200",
    category: "cruiser", price: 195000, searches: 142600, rating: 4.5, availability: "New",
    fuel: "Petrol", transmission: "6MT (belt drive)", cooling: "Air/Oil", abs: "Dual-channel",
    power: "82 hp", torque: "155 Nm", mileage: "18.2 km/l", kerb: "268 kg", seatHeight: "690 mm",
    tags: ["Torque Focused"], hue: 25,
    highlight: "Low-slung V-twin boulevard king",
    colors: ["Vintage Bronze", "Jet Black"],
    variants: [{ name: "Titan 1200", price: 195000, power: "82 hp", mileage: "18.2 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "1,198cc V-twin", "Power": "82 hp", "Torque": "155 Nm @ 3,000 rpm", "Transmission": "6-speed, belt final drive", "Cooling": "Air/oil" },
      "Chassis & Dimensions": { "Kerb weight": "268 kg", "Seat height": "690 mm", "Fuel tank": "18.9 L" },
      "Braking & Suspension": { "ABS": "Dual-channel", "Front suspension": "49 mm telescopic", "Warranty": "2 yr unlimited" },
    },
    pros: ["Armchair seat height", "Thumping low-end"], cons: ["Heavy at walking pace"],
    reviews: [R("Hank B.", 4.5, "Highway hypnotherapy", "155 Nm at 3k means overtakes happen in sixth. Belt drive = clean jeans.", { helpful: 26 })],
  },
  {
    id: "volt-havoc-sx", type: "bike", brand: "Volt Havoc", model: "SX",
    category: "electric", price: 168000, searches: 298400, rating: 4.6, availability: "New",
    fuel: "Electric", transmission: "Automatic", cooling: "Liquid (battery)", abs: "Dual-channel, regen-linked",
    power: "107 hp", torque: "220 Nm", mileage: "210 km range", kerb: "196 kg", seatHeight: "800 mm", chargeTime: "0–80% in 40 min",
    tags: ["EV Ready", "City Agile"], hue: 175,
    highlight: "Instant-torque electric streetfighter",
    colors: ["Volt Teal", "Graphite"],
    variants: [
      { name: "SX",      price: 168000, power: "107 hp", mileage: "210 km range" },
      { name: "SX Long Range", price: 194000, power: "107 hp", mileage: "265 km range" },
    ],
    specs: {
      "Powertrain": { "Motor": "Mid-drive PMSM", "Power": "107 hp", "Torque": "220 Nm (instant)", "Battery": "17.3 kWh", "Range (city)": "210 km", "Charge time": "0–80% in 40 min (DC)", "Riding modes": "4 + regen tuning" },
      "Chassis & Dimensions": { "Kerb weight": "196 kg", "Seat height": "800 mm" },
      "Braking & Suspension": { "ABS": "Dual-channel, regen-blended", "Front suspension": "USD forks", "Warranty": "5 yr battery" },
    },
    pros: ["220 Nm off the line", "Near-zero maintenance"], cons: ["Fast-charger network still growing"],
    reviews: [
      R("Lea T.", 5, "Traffic-light champion", "Nothing at a signal touches it. Charging at home every third day.", { helpful: 58 }),
      R("Om P.", 4, "Brilliant, with a caveat", "Weekend range anxiety is real outside the city. In town, it's perfect.", { verified: false, ownership: "Test drive", helpful: 12 }),
    ],
  },
  {
    id: "windlance-tourer-gt650", type: "bike", brand: "Windlance", model: "Tourer GT650",
    category: "touring", price: 142000, searches: 96700, rating: 4.4, availability: "New",
    fuel: "Petrol", transmission: "6MT", cooling: "Liquid", abs: "Dual-channel",
    power: "68 hp", torque: "64 Nm", mileage: "22.4 km/l", kerb: "228 kg", seatHeight: "790 mm",
    tags: ["Torque Focused"], hue: 210,
    highlight: "Panniers, cruise control, 500 km days",
    colors: ["Horizon Blue", "Sand"],
    variants: [{ name: "GT650", price: 142000, power: "68 hp", mileage: "22.4 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "649cc parallel-twin", "Power": "68 hp", "Torque": "64 Nm", "Transmission": "6-speed", "Cruise control": "Standard" },
      "Chassis & Dimensions": { "Kerb weight": "228 kg (with panniers)", "Seat height": "790 mm", "Fuel tank": "23 L" },
      "Braking & Suspension": { "ABS": "Dual-channel", "Screen": "Electrically adjustable", "Warranty": "3 yr" },
    },
    pros: ["600 km tank range", "All-day comfort"], cons: ["Not a canyon carver"],
    reviews: [R("Sana M.", 4.5, "Borders? Which borders?", "Did 4 countries in 6 days. The seat deserves an award.", { helpful: 21 })],
  },
  {
    id: "cobalt-strada-125", type: "bike", brand: "Cobalt Cycles", model: "Strada 125",
    category: "scooter", price: 38000, searches: 342100, rating: 4.3, availability: "New",
    fuel: "Petrol", transmission: "CVT automatic", cooling: "Air", abs: "CBS",
    power: "9.8 hp", torque: "10.4 Nm", mileage: "52 km/l", kerb: "108 kg", seatHeight: "765 mm",
    tags: ["City Agile"], hue: 55,
    highlight: "The city's favourite 52 km/l scooter",
    colors: ["Mango Yellow", "Ash", "Wine Red"],
    variants: [
      { name: "Std",   price: 38000, power: "9.8 hp", mileage: "52 km/l" },
      { name: "Smart", price: 43500, power: "9.8 hp", mileage: "52 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "124cc single", "Power": "9.8 hp", "Torque": "10.4 Nm", "Transmission": "CVT", "Mileage": "52 km/l" },
      "Chassis & Dimensions": { "Kerb weight": "108 kg", "Seat height": "765 mm", "Under-seat storage": "24 L", "Fuel tank": "5.5 L" },
      "Braking & Suspension": { "Braking": "CBS, front disc (Smart)", "Warranty": "5 yr engine" },
    },
    pros: ["52 km/l real world", "Fits a full-face lid under the seat"], cons: ["Two-up highway runs are brave"],
    reviews: [
      R("Vikram J.", 4.5, "Family workhorse", "Three years, 30,000 km, one belt change. That's the whole story.", { helpful: 71 }),
    ],
  },
  {
    id: "meridian-nomad-450", type: "bike", brand: "Meridian", model: "Nomad 450",
    category: "adventure", price: 118000, searches: 201300, rating: 4.6, availability: "New",
    fuel: "Petrol", transmission: "6MT", cooling: "Liquid", abs: "Switchable dual-channel",
    power: "40 hp", torque: "40 Nm", mileage: "28.5 km/l", kerb: "185 kg", seatHeight: "825 mm",
    tags: ["Torque Focused", "City Agile"], hue: 130,
    highlight: "21-inch front, rally-bred midweight ADV",
    colors: ["Expedition Green", "Dune White"],
    variants: [{ name: "Nomad 450", price: 118000, power: "40 hp", mileage: "28.5 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "452cc single, liquid-cooled", "Power": "40 hp", "Torque": "40 Nm", "Transmission": "6-speed, slip-assist clutch" },
      "Chassis & Dimensions": { "Kerb weight": "185 kg", "Seat height": "825 mm", "Ground clearance": "230 mm", "Fuel tank": "16 L", "Front wheel": "21-inch spoked" },
      "Braking & Suspension": { "ABS": "Switchable (off-road mode)", "Suspension travel": "200 mm F / 195 mm R", "Warranty": "3 yr" },
    },
    pros: ["Genuine off-road chops", "Tractable single"], cons: ["Tall for shorter riders"],
    reviews: [
      R("Ida S.", 5, "Fire roads for breakfast", "Switchable ABS and that 21-inch front change everything off-tarmac.", { helpful: 35 }),
      R("Neel G.", 4, "Daily + weekend hero", "Commutes fine, then eats trails on Sunday. Wind protection could be taller.", { helpful: 14 }),
    ],
  },
  {
    id: "ryujin-street-770", type: "bike", brand: "Ryujin", model: "Street 770",
    category: "naked", price: 155000, searches: 187900, rating: 4.5, availability: "New",
    fuel: "Petrol", transmission: "6MT", cooling: "Liquid", abs: "Cornering, dual-channel",
    power: "115 hp", torque: "77 Nm", mileage: "19.6 km/l", kerb: "184 kg", seatHeight: "815 mm",
    tags: ["Track Inspired", "City Agile"], hue: 285,
    highlight: "Hooligan-spec naked with cornering ABS",
    colors: ["Ultraviolet", "Titanium"],
    variants: [{ name: "Street 770", price: 155000, power: "115 hp", mileage: "19.6 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "770cc parallel-twin", "Power": "115 hp", "Torque": "77 Nm", "Transmission": "6-speed, quickshifter opt." },
      "Chassis & Dimensions": { "Kerb weight": "184 kg", "Seat height": "815 mm", "Fuel tank": "15 L" },
      "Braking & Suspension": { "ABS": "Cornering", "Front brake": "Dual 300 mm", "Warranty": "3 yr" },
    },
    pros: ["Torque everywhere", "Upright comfort"], cons: ["Windblast past 130"],
    reviews: [R("Cal R.", 4.5, "Grin factory", "Wheelie control set to 'fun'. Commutes Monday, scratches Sunday.", { helpful: 29 })],
  },
  {
    id: "apexforge-vagabond-350", type: "bike", brand: "Apex Forge", model: "Vagabond 350",
    category: "caferacer", price: 89000, searches: 156800, rating: 4.2, availability: "New",
    fuel: "Petrol", transmission: "5MT", cooling: "Air", abs: "Dual-channel",
    power: "27 hp", torque: "30 Nm", mileage: "32 km/l", kerb: "158 kg", seatHeight: "780 mm",
    tags: [], hue: 18,
    highlight: "Clip-ons, chrome and coffee",
    colors: ["Espresso Brown", "Cream"],
    variants: [{ name: "Vagabond", price: 89000, power: "27 hp", mileage: "32 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "349cc single, air-cooled", "Power": "27 hp", "Torque": "30 Nm", "Transmission": "5-speed" },
      "Chassis & Dimensions": { "Kerb weight": "158 kg", "Seat height": "780 mm", "Fuel tank": "13 L" },
      "Braking & Suspension": { "ABS": "Dual-channel", "Warranty": "2 yr" },
    },
    pros: ["Timeless looks", "Friendly power"], cons: ["Firm café seat"],
    reviews: [],
  },
  {
    id: "cobalt-metro-e", type: "bike", brand: "Cobalt Cycles", model: "Metro-E",
    category: "electric", price: 52000, searches: 265700, rating: 4.1, availability: "New",
    fuel: "Electric", transmission: "Automatic", cooling: "Air", abs: "CBS + regen",
    power: "8.2 hp", torque: "38 Nm", mileage: "95 km range", kerb: "92 kg", seatHeight: "760 mm", chargeTime: "0–100% in 3.5 h",
    tags: ["EV Ready", "City Agile"], hue: 150,
    highlight: "Swappable-battery electric commuter",
    colors: ["Mint", "Charcoal"],
    variants: [{ name: "Metro-E", price: 52000, power: "8.2 hp", mileage: "95 km range" }],
    specs: {
      "Powertrain": { "Motor": "Hub-mounted BLDC", "Power": "8.2 hp", "Torque": "38 Nm", "Battery": "3.2 kWh swappable ×2", "Range": "95 km", "Charge time": "3.5 h (home)" },
      "Chassis & Dimensions": { "Kerb weight": "92 kg", "Seat height": "760 mm", "Storage": "26 L" },
      "Braking & Suspension": { "Braking": "CBS + regenerative", "Warranty": "3 yr battery" },
    },
    pros: ["Swap batteries in seconds", "Featherweight"], cons: ["Modest hill performance"],
    reviews: [R("Anu R.", 4, "City sorted", "Office is 11 km away. I charge twice a week at my desk. Done.", { helpful: 17 })],
  },
  {
    id: "windlance-courier-110", type: "bike", brand: "Windlance", model: "Courier 110",
    category: "commuter", price: 31000, searches: 289600, rating: 4.0, availability: "New",
    fuel: "Petrol", transmission: "4MT", cooling: "Air", abs: "CBS",
    power: "8.6 hp", torque: "9.3 Nm", mileage: "64 km/l", kerb: "99 kg", seatHeight: "790 mm",
    tags: ["City Agile"], hue: 75,
    highlight: "64 km/l. That's it. That's the headline.",
    colors: ["Silver", "Black-Red"],
    variants: [{ name: "Courier", price: 31000, power: "8.6 hp", mileage: "64 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "109cc single", "Power": "8.6 hp", "Mileage": "64 km/l", "Transmission": "4-speed" },
      "Chassis & Dimensions": { "Kerb weight": "99 kg", "Fuel tank": "9.5 L" },
      "Braking & Suspension": { "Braking": "CBS drum", "Warranty": "5 yr engine" },
    },
    pros: ["Cheapest possible commutes"], cons: ["Basic everything else"],
    reviews: [],
  },
  {
    id: "ryujin-shogun-1400gt", type: "bike", brand: "Ryujin", model: "Shogun 1400 GT",
    category: "touring", price: 385000, searches: 76200, rating: 4.8, availability: "New",
    fuel: "Petrol", transmission: "6MT (DCT opt.)", cooling: "Liquid", abs: "Cornering, linked",
    power: "160 hp", torque: "170 Nm", mileage: "16.4 km/l", kerb: "312 kg", seatHeight: "750 mm",
    tags: ["Torque Focused"], hue: 240,
    highlight: "Continental ballistic tourer with radar cruise",
    colors: ["Imperial Blue", "Storm Silver"],
    variants: [
      { name: "GT",     price: 385000, power: "160 hp", mileage: "16.4 km/l" },
      { name: "GT DCT", price: 412000, power: "160 hp", mileage: "16.8 km/l" },
    ],
    specs: {
      "Engine & Performance": { "Engine": "1,340cc inline-4", "Power": "160 hp", "Torque": "170 Nm", "Transmission": "6MT or 7-speed DCT", "Radar cruise": "Front + rear" },
      "Chassis & Dimensions": { "Kerb weight": "312 kg", "Seat height": "750 mm", "Fuel tank": "25 L", "Luggage": "121 L total" },
      "Braking & Suspension": { "ABS": "Cornering, semi-active suspension", "Warranty": "3 yr unlimited" },
    },
    pros: ["Radar cruise on a bike", "Magic-carpet suspension"], cons: ["It's a small building"],
    reviews: [R("Jorge V.", 5, "Continent crusher", "1,100 km in a day and I walked away whistling. DCT is witchcraft.", { variant: "GT DCT", helpful: 24 })],
  },
  {
    id: "meridian-blitz-200", type: "bike", brand: "Meridian", model: "Blitz 200",
    category: "sports", price: 62000, searches: 244100, rating: 4.3, availability: "New",
    fuel: "Petrol", transmission: "6MT", cooling: "Liquid", abs: "Single-channel",
    power: "24 hp", torque: "18.7 Nm", mileage: "38 km/l", kerb: "142 kg", seatHeight: "805 mm",
    tags: ["Track Inspired", "City Agile"], hue: 5,
    highlight: "Everyone's first full fairing",
    colors: ["Race Red", "Track Blue"],
    variants: [{ name: "Blitz 200", price: 62000, power: "24 hp", mileage: "38 km/l" }],
    specs: {
      "Engine & Performance": { "Engine": "199cc single, liquid-cooled", "Power": "24 hp", "Torque": "18.7 Nm", "Transmission": "6-speed" },
      "Chassis & Dimensions": { "Kerb weight": "142 kg", "Seat height": "805 mm", "Fuel tank": "11 L" },
      "Braking & Suspension": { "ABS": "Single-channel", "Warranty": "2 yr" },
    },
    pros: ["Big-bike feel, small-bike bills"], cons: ["Pillion perch is symbolic"],
    reviews: [R("Tara B.", 4.5, "Gateway drug", "My first faired bike. Light, forgiving, and looks properly quick.", { helpful: 40 })],
  },
];

export const BRANDS = [...new Set(VEHICLES.map(v => v.brand))].map(b => ({
  name: b,
  count: VEHICLES.filter(v => v.brand === b).length,
  types: [...new Set(VEHICLES.filter(v => v.brand === b).map(v => v.type))],
}));

export const CATEGORY_MAP = { car: CAR_CATEGORIES, bike: BIKE_CATEGORIES };

export function catLabel(type, id) {
  const c = (CATEGORY_MAP[type] || []).find(c => c.id === id);
  return c ? c.label : id;
}
