package com.autohub.shared.infrastructure.bootstrap;

import com.autohub.adminops.infrastructure.persistence.BodyTypeEntity;
import com.autohub.adminops.infrastructure.persistence.BodyTypeRepository;
import com.autohub.adminops.infrastructure.persistence.CategoryEntity;
import com.autohub.adminops.infrastructure.persistence.CategoryRepository;
import com.autohub.adminops.infrastructure.persistence.FuelTypeEntity;
import com.autohub.adminops.infrastructure.persistence.FuelTypeRepository;
import com.autohub.adminops.infrastructure.persistence.NamedMasterEntity;
import com.autohub.adminops.infrastructure.persistence.ReportReasonEntity;
import com.autohub.adminops.infrastructure.persistence.ReportReasonRepository;
import com.autohub.adminops.infrastructure.persistence.ReviewTagEntity;
import com.autohub.adminops.infrastructure.persistence.ReviewTagRepository;
import com.autohub.adminops.infrastructure.persistence.TourCategoryEntity;
import com.autohub.adminops.infrastructure.persistence.TourCategoryRepository;
import com.autohub.adminops.infrastructure.persistence.TransmissionEntity;
import com.autohub.adminops.infrastructure.persistence.TransmissionRepository;
import com.autohub.identity.infrastructure.persistence.PermissionEntity;
import com.autohub.identity.infrastructure.persistence.PermissionJpaRepository;
import com.autohub.identity.infrastructure.persistence.RoleEntity;
import com.autohub.identity.infrastructure.persistence.RoleJpaRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.core.annotation.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collectors;

/**
 * Seeds RBAC (roles, permissions, mappings) and starter master data for the {@code local}
 * profile, where Flyway is disabled and the schema is generated by Hibernate. Mirrors the
 * Flyway V2 seed used on PostgreSQL. Idempotent. Runs before {@link BootstrapDataInitializer}.
 */
@Component
@Profile("local")
@Order(10)
public class LocalDataSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(LocalDataSeeder.class);

    private static final List<String> PERMISSIONS = List.of(
            "post:create", "post:update", "post:publish", "post:moderate", "image:upload",
            "review:create", "comment:create", "comment:moderate", "listing:create", "listing:approve",
            "offer:create", "travel:create", "tour:create", "community:create", "kyc:submit",
            "kyc:review", "master:manage", "user:manage", "role:manage", "report:review", "audit:read");

    private static final Map<String, List<String>> ROLE_PERMISSIONS = Map.of(
            "SUPER_ADMIN", PERMISSIONS,
            "ADMIN", PERMISSIONS.stream().filter(p -> !p.equals("role:manage")).toList(),
            "MODERATOR", List.of("post:moderate", "comment:moderate", "report:review", "listing:approve", "audit:read"),
            "SELLER", List.of("listing:create", "kyc:submit", "image:upload", "post:create"),
            "BUYER", List.of("offer:create", "kyc:submit"),
            "AUTHOR", List.of("post:create", "post:update", "post:publish", "image:upload", "travel:create", "tour:create"),
            "MEMBER", List.of("comment:create", "review:create", "community:create"),
            "GUEST", List.of());

    private static final Map<String, String> ROLE_NAMES = Map.of(
            "SUPER_ADMIN", "Super Admin", "ADMIN", "Administrator", "MODERATOR", "Moderator",
            "SELLER", "Seller", "BUYER", "Buyer", "AUTHOR", "Author", "MEMBER", "Member", "GUEST", "Guest");

    private final PermissionJpaRepository permissionJpa;
    private final RoleJpaRepository roleJpa;
    private final FuelTypeRepository fuelTypes;
    private final BodyTypeRepository bodyTypes;
    private final TransmissionRepository transmissions;
    private final CategoryRepository categories;
    private final TourCategoryRepository tourCategories;
    private final ReviewTagRepository reviewTags;
    private final ReportReasonRepository reportReasons;

    public LocalDataSeeder(PermissionJpaRepository permissionJpa, RoleJpaRepository roleJpa,
                           FuelTypeRepository fuelTypes, BodyTypeRepository bodyTypes,
                           TransmissionRepository transmissions, CategoryRepository categories,
                           TourCategoryRepository tourCategories, ReviewTagRepository reviewTags,
                           ReportReasonRepository reportReasons) {
        this.permissionJpa = permissionJpa;
        this.roleJpa = roleJpa;
        this.fuelTypes = fuelTypes;
        this.bodyTypes = bodyTypes;
        this.transmissions = transmissions;
        this.categories = categories;
        this.tourCategories = tourCategories;
        this.reviewTags = reviewTags;
        this.reportReasons = reportReasons;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        if (roleJpa.count() > 0) {
            return; // already seeded
        }

        // Permissions
        Map<String, PermissionEntity> permByCode = PERMISSIONS.stream()
                .map(code -> permissionJpa.save(new PermissionEntity(UUID.randomUUID(), code, code)))
                .collect(Collectors.toMap(PermissionEntity::getCode, Function.identity()));

        // Roles + mappings
        ROLE_PERMISSIONS.forEach((code, perms) -> {
            RoleEntity role = new RoleEntity(UUID.randomUUID(), code, ROLE_NAMES.get(code), ROLE_NAMES.get(code));
            Set<PermissionEntity> assigned = perms.stream().map(permByCode::get).collect(Collectors.toCollection(HashSet::new));
            role.setPermissions(assigned);
            roleJpa.save(role);
        });

        // Starter masters
        seed(fuelTypes, FuelTypeEntity::new, List.of("Petrol", "Diesel", "Electric", "Hybrid", "CNG"));
        seed(bodyTypes, BodyTypeEntity::new, List.of("Hatchback", "Sedan", "SUV", "Coupe", "Cruiser", "Sportbike", "Scooter"));
        seed(transmissions, TransmissionEntity::new, List.of("Manual", "Automatic", "AMT", "CVT", "DCT"));
        seed(categories, CategoryEntity::new, List.of("Car", "Bike"));
        seed(tourCategories, TourCategoryEntity::new, List.of("Road Trip", "Adventure", "City Tour", "Off-road", "Coastal"));
        seed(reviewTags, ReviewTagEntity::new, List.of("Performance", "Comfort", "Value", "Reliability", "Design"));
        seed(reportReasons, ReportReasonEntity::new, List.of("Spam", "Fraud", "Offensive", "Wrong Category", "Duplicate"));

        log.info("[local] Seeded {} permissions, {} roles and starter masters (H2)", PERMISSIONS.size(), ROLE_PERMISSIONS.size());
    }

    private <T extends NamedMasterEntity> void seed(JpaRepository<T, UUID> repo,
                                                    Supplier<T> factory, List<String> names) {
        for (String name : names) {
            T entity = factory.get();
            entity.setId(UUID.randomUUID());
            entity.setName(name);
            entity.setActive(true);
            repo.save(entity);
        }
    }
}
